<?xml version="1.0" encoding="utf-8"?><Database Name="MyStudy" Class="MyStudyDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-9OTSLON;Initial Catalog=MyStudy;Integrated Security=True" SettingsObjectName="MyStudy.DAL.Properties.Settings" SettingsPropertyName="MyStudyConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="Users">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="StuNumber" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Colleges" Member="Colleges">
    <Type Name="Colleges">
      <Column Name="CollegeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="College" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="StuNumber" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Provinces" Member="Provinces">
    <Type Name="Provinces">
      <Column Name="ProvId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProvName" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="ProvAB" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="ProvNo" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Zhx34" Member="Zhx34">
    <Type Name="Zhx34">
      <Column Name="Zhx34Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ZhxName" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="ZhxProv" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.FirstMajors" Member="FirstMajors">
    <Type Name="FirstMajors">
      <Column Name="FirstMajorId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstMajorName" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="FirstMajorNo" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Association Name="FirstMajors_SecondMajors" Member="SecondMajors" ThisKey="FirstMajorId" OtherKey="FirstMajorId" Type="SecondMajors" />
    </Type>
  </Table>
  <Table Name="dbo.SecondMajors" Member="SecondMajors">
    <Type Name="SecondMajors">
      <Column Name="SecondMajorId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SecondMajorName" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="SecondMajorNo" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="FirstMajorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SecondMajors_ThirdMajors" Member="ThirdMajors" ThisKey="SecondMajorId" OtherKey="SecondMajorId" Type="ThirdMajors" />
      <Association Name="FirstMajors_SecondMajors" Member="FirstMajors" ThisKey="FirstMajorId" OtherKey="FirstMajorId" Type="FirstMajors" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThirdMajors" Member="ThirdMajors">
    <Type Name="ThirdMajors">
      <Column Name="ThirdMajorId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ThirdMajorName" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="ThirdMajorNo" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="SecondMajorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SecondMajors_ThirdMajors" Member="SecondMajors" ThisKey="SecondMajorId" OtherKey="SecondMajorId" Type="SecondMajors" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Admins" Member="Admins">
    <Type Name="Admins">
      <Column Name="AdminId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AdminNo" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.NetView" Member="NetView">
    <Type Name="NetView">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IPAddr" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="IPSrc" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
</Database>